name: mntts2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2022.6.15=py37h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1p=h5eee18b_0
  - pip=21.2.2=py37h06a4308_0
  - python=3.7.13=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=61.2.0=py37h06a4308_0
  - sqlite=3.38.5=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - absl-py
    - appdirs
    - astunparse
    - audioread
    - cached-property
    - cachetools
    - cffi
    - charset-normalizer
    - clang
    - click
    - cycler
    - cython
    - dataclasses
    - decorator
    - distance
    - filelock
    - flatbuffers
    - fonttools
    - g2p-en
    - g2pm
    - gast
    - google-auth
    - google-auth-oauthlib
    - google-pasta
    - grpcio
    - h5py
    - huggingface-hub
    - idna
    - importlib-metadata
    - inflect
    - jamo
    - joblib
    - keras
    - keras-preprocessing
    - kiwisolver
    - librosa
    - llvmlite
    - markdown
    - matplotlib
    - nltk
    - numba
    - numpy
    - oauthlib
    - opt-einsum
    - packaging
    - pillow
    - pooch
    - protobuf
    - pyasn1
    - pyasn1-modules
    - pycparser
    - pyparsing
    - pypinyin
    - python-dateutil
    - pyworld
    - pyyaml
    - regex==2022.7.9
    - requests
    - requests-oauthlib
    - resampy
    - rsa
    - scikit-learn
    - scipy
    - six
    - soundfile==0.10.3.post1
    - tensorboard
    - tensorboard-data-server
    - tensorboard-plugin-wit
    - tensorflow-addons
    - tensorflow-estimator
    - tensorflow-gpu
    - tensorflowtts
    - termcolor
    - textgrid
    - threadpoolctl
    - tqdm
    - typeguard
    - typing-extensions
    - unidecode
    - urllib3
    - werkzeug
    - wrapt
    - zipp
prefix: /home/anaconda3/envs/mntts3
